package sop_corba.GestionUsuariosIntPackage;


/**
* sop_corba/GestionUsuariosIntPackage/ListaUsuariosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* domingo 3 de octubre de 2021 05:25:26 PM COT
*/

public final class ListaUsuariosHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.clsUsuariosDTO value[] = null;

  public ListaUsuariosHolder ()
  {
  }

  public ListaUsuariosHolder (sop_corba.clsUsuariosDTO[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.GestionUsuariosIntPackage.ListaUsuariosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.GestionUsuariosIntPackage.ListaUsuariosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.GestionUsuariosIntPackage.ListaUsuariosHelper.type ();
  }

}
