package sop_corba;


/**
* sop_corba/_GestionAnteproyectosIntStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* domingo 3 de octubre de 2021 05:25:26 PM COT
*/

public class _GestionAnteproyectosIntStub extends org.omg.CORBA.portable.ObjectImpl implements sop_corba.GestionAnteproyectosInt
{

  public boolean registrarFormatoA (sop_corba.clsFormatoADTO objFormatoA)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registrarFormatoA", true);
                sop_corba.clsFormatoADTOHelper.write ($out, objFormatoA);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return registrarFormatoA (objFormatoA        );
            } finally {
                _releaseReply ($in);
            }
  } // registrarFormatoA

  public boolean AsignarFormatoB (sop_corba.clsFormatoBDTO objFormatoB)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("AsignarFormatoB", true);
                sop_corba.clsFormatoBDTOHelper.write ($out, objFormatoB);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return AsignarFormatoB (objFormatoB        );
            } finally {
                _releaseReply ($in);
            }
  } // AsignarFormatoB

  public boolean RegistrarFormatoC (sop_corba.clsFormatoCDTO objFormatoC)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("RegistrarFormatoC", true);
                sop_corba.clsFormatoCDTOHelper.write ($out, objFormatoC);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return RegistrarFormatoC (objFormatoC        );
            } finally {
                _releaseReply ($in);
            }
  } // RegistrarFormatoC

  public boolean RegistrarFormatoD (sop_corba.clsFormatoDDTO objFormatoD)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("RegistrarFormatoD", true);
                sop_corba.clsFormatoDDTOHelper.write ($out, objFormatoD);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return RegistrarFormatoD (objFormatoD        );
            } finally {
                _releaseReply ($in);
            }
  } // RegistrarFormatoD

  public int ModificarFormatoB (sop_corba.clsFormatoBDTO objFormatoB)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("ModificarFormatoB", true);
                sop_corba.clsFormatoBDTOHelper.write ($out, objFormatoB);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return ModificarFormatoB (objFormatoB        );
            } finally {
                _releaseReply ($in);
            }
  } // ModificarFormatoB

  public int ConsultarConceptoC (int prmCodigo)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("ConsultarConceptoC", true);
                $out.write_long (prmCodigo);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return ConsultarConceptoC (prmCodigo        );
            } finally {
                _releaseReply ($in);
            }
  } // ConsultarConceptoC

  public int ConsultarConceptoD (int prmCodigo)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("ConsultarConceptoD", true);
                $out.write_long (prmCodigo);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return ConsultarConceptoD (prmCodigo        );
            } finally {
                _releaseReply ($in);
            }
  } // ConsultarConceptoD

  public sop_corba.clsConceptosDTO consultarConceptos (int prmCodigo)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("consultarConceptos", true);
                $out.write_long (prmCodigo);
                $in = _invoke ($out);
                sop_corba.clsConceptosDTO $result = sop_corba.clsConceptosDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return consultarConceptos (prmCodigo        );
            } finally {
                _releaseReply ($in);
            }
  } // consultarConceptos

  public int VerificarAnteproyecto (int prmCodigo)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("VerificarAnteproyecto", true);
                $out.write_long (prmCodigo);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return VerificarAnteproyecto (prmCodigo        );
            } finally {
                _releaseReply ($in);
            }
  } // VerificarAnteproyecto

  public int SolicitarCodigo ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("SolicitarCodigo", true);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return SolicitarCodigo (        );
            } finally {
                _releaseReply ($in);
            }
  } // SolicitarCodigo

  public int ConsultarAnteproyectoB (int codigo)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("ConsultarAnteproyectoB", true);
                $out.write_long (codigo);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return ConsultarAnteproyectoB (codigo        );
            } finally {
                _releaseReply ($in);
            }
  } // ConsultarAnteproyectoB

  public int verificarAsignacion (int CodAnteproyecto, int idEvaluador)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("verificarAsignacion", true);
                $out.write_long (CodAnteproyecto);
                $out.write_long (idEvaluador);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return verificarAsignacion (CodAnteproyecto, idEvaluador        );
            } finally {
                _releaseReply ($in);
            }
  } // verificarAsignacion

  public sop_corba.clsFormatoBDTO[] listaAteproyectosAsignados (int idEvaluador)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listaAteproyectosAsignados", true);
                $out.write_long (idEvaluador);
                $in = _invoke ($out);
                sop_corba.clsFormatoBDTO $result[] = sop_corba.GestionAnteproyectosIntPackage.formatosBHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listaAteproyectosAsignados (idEvaluador        );
            } finally {
                _releaseReply ($in);
            }
  } // listaAteproyectosAsignados

  public sop_corba.clsFormatoBDTO[] listaAteproyectosB ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listaAteproyectosB", true);
                $in = _invoke ($out);
                sop_corba.clsFormatoBDTO $result[] = sop_corba.GestionAnteproyectosIntPackage.formatosBHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listaAteproyectosB (        );
            } finally {
                _releaseReply ($in);
            }
  } // listaAteproyectosB

  public sop_corba.clsFormatoCDTO[] listaAteproyectosC ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listaAteproyectosC", true);
                $in = _invoke ($out);
                sop_corba.clsFormatoCDTO $result[] = sop_corba.GestionAnteproyectosIntPackage.formatosCHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listaAteproyectosC (        );
            } finally {
                _releaseReply ($in);
            }
  } // listaAteproyectosC

  public sop_corba.clsFormatoDDTO[] listaAteproyectosD ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listaAteproyectosD", true);
                $in = _invoke ($out);
                sop_corba.clsFormatoDDTO $result[] = sop_corba.GestionAnteproyectosIntPackage.formatosDHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listaAteproyectosD (        );
            } finally {
                _releaseReply ($in);
            }
  } // listaAteproyectosD

  public sop_corba.clsFormatoADTO[] listaSinAsignar ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listaSinAsignar", true);
                $in = _invoke ($out);
                sop_corba.clsFormatoADTO $result[] = sop_corba.GestionAnteproyectosIntPackage.formatosAHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listaSinAsignar (        );
            } finally {
                _releaseReply ($in);
            }
  } // listaSinAsignar

  public int[] listaAntNoRemitidos (int idDirector)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listaAntNoRemitidos", true);
                $out.write_long (idDirector);
                $in = _invoke ($out);
                int $result[] = sop_corba.GestionAnteproyectosIntPackage.listaAnteproyectosNoRemitidosHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listaAntNoRemitidos (idDirector        );
            } finally {
                _releaseReply ($in);
            }
  } // listaAntNoRemitidos

  public boolean remitirAnteproyecto (int codAnteproyecto)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("remitirAnteproyecto", true);
                $out.write_long (codAnteproyecto);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return remitirAnteproyecto (codAnteproyecto        );
            } finally {
                _releaseReply ($in);
            }
  } // remitirAnteproyecto

  public int[] listaAntRemitidos ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listaAntRemitidos", true);
                $in = _invoke ($out);
                int $result[] = sop_corba.GestionAnteproyectosIntPackage.listaAnteproyectosRemitidosHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listaAntRemitidos (        );
            } finally {
                _releaseReply ($in);
            }
  } // listaAntRemitidos

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/GestionAnteproyectosInt:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _GestionAnteproyectosIntStub
