package sop_corba;


/**
* sop_corba/clsConceptosDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* domingo 3 de octubre de 2021 08:29:51 PM COT
*/

public final class clsConceptosDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String Concepto1 = null;
  public String Concepto2 = null;

  public clsConceptosDTO ()
  {
  } // ctor

  public clsConceptosDTO (String _Concepto1, String _Concepto2)
  {
    Concepto1 = _Concepto1;
    Concepto2 = _Concepto2;
  } // ctor

} // class clsConceptosDTO
