package sop_corba;


/**
* sop_corba/clsFormatosDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* domingo 3 de octubre de 2021 08:29:51 PM COT
*/

public final class clsFormatosDTO implements org.omg.CORBA.portable.IDLEntity
{
  public sop_corba.clsFormatoADTO formatoA = null;
  public sop_corba.clsFormatoBDTO formatoB1 = null;
  public sop_corba.clsFormatoBDTO formateB2 = null;
  public sop_corba.clsFormatoCDTO formatoC = null;
  public sop_corba.clsFormatoDDTO formatoD = null;
  public int codAnteproyecto = (int)0;

  public clsFormatosDTO ()
  {
  } // ctor

  public clsFormatosDTO (sop_corba.clsFormatoADTO _formatoA, sop_corba.clsFormatoBDTO _formatoB1, sop_corba.clsFormatoBDTO _formateB2, sop_corba.clsFormatoCDTO _formatoC, sop_corba.clsFormatoDDTO _formatoD, int _codAnteproyecto)
  {
    formatoA = _formatoA;
    formatoB1 = _formatoB1;
    formateB2 = _formateB2;
    formatoC = _formatoC;
    formatoD = _formatoD;
    codAnteproyecto = _codAnteproyecto;
  } // ctor

} // class clsFormatosDTO
