package sop_corba;

/**
* sop_corba/clsFormatoCDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* domingo 3 de octubre de 2021 05:25:26 PM COT
*/

public final class clsFormatoCDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.clsFormatoCDTO value = null;

  public clsFormatoCDTOHolder ()
  {
  }

  public clsFormatoCDTOHolder (sop_corba.clsFormatoCDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.clsFormatoCDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.clsFormatoCDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.clsFormatoCDTOHelper.type ();
  }

}
