package sop_corba;


/**
* sop_corba/clsFormatoADTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* domingo 3 de octubre de 2021 08:29:51 PM COT
*/

public final class clsFormatoADTO implements org.omg.CORBA.portable.IDLEntity
{
  public int codAnteproyecto = (int)0;
  public String nomPrograma = null;
  public String tituloAnteproyecto = null;
  public String nomEstudiante1 = null;
  public int codEstudiante1 = (int)0;
  public String nomEstudiante2 = null;
  public int codEstudiante2 = (int)0;
  public String nomDirector = null;
  public String nomCoDirector = null;
  public String objetivosAnteproyecto = null;
  public int codDirector = (int)0;
  public int flujo = (int)0;

  public clsFormatoADTO ()
  {
  } // ctor

  public clsFormatoADTO (int _codAnteproyecto, String _nomPrograma, String _tituloAnteproyecto, String _nomEstudiante1, int _codEstudiante1, String _nomEstudiante2, int _codEstudiante2, String _nomDirector, String _nomCoDirector, String _objetivosAnteproyecto, int _codDirector, int _flujo)
  {
    codAnteproyecto = _codAnteproyecto;
    nomPrograma = _nomPrograma;
    tituloAnteproyecto = _tituloAnteproyecto;
    nomEstudiante1 = _nomEstudiante1;
    codEstudiante1 = _codEstudiante1;
    nomEstudiante2 = _nomEstudiante2;
    codEstudiante2 = _codEstudiante2;
    nomDirector = _nomDirector;
    nomCoDirector = _nomCoDirector;
    objetivosAnteproyecto = _objetivosAnteproyecto;
    codDirector = _codDirector;
    flujo = _flujo;
  } // ctor

} // class clsFormatoADTO
