package sop_corba;


/**
* sop_corba/clsFormatoADTOHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* domingo 3 de octubre de 2021 07:51:32 PM COT
*/

abstract public class clsFormatoADTOHelper
{
  private static String  _id = "IDL:sop_corba/clsFormatoADTO:1.0";

  public static void insert (org.omg.CORBA.Any a, sop_corba.clsFormatoADTO that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static sop_corba.clsFormatoADTO extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [12];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "codAnteproyecto",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "nomPrograma",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "tituloAnteproyecto",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "nomEstudiante1",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[4] = new org.omg.CORBA.StructMember (
            "codEstudiante1",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[5] = new org.omg.CORBA.StructMember (
            "nomEstudiante2",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[6] = new org.omg.CORBA.StructMember (
            "codEstudiante2",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[7] = new org.omg.CORBA.StructMember (
            "nomDirector",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[8] = new org.omg.CORBA.StructMember (
            "nomCoDirector",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[9] = new org.omg.CORBA.StructMember (
            "objetivosAnteproyecto",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[10] = new org.omg.CORBA.StructMember (
            "codDirector",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[11] = new org.omg.CORBA.StructMember (
            "flujo",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (sop_corba.clsFormatoADTOHelper.id (), "clsFormatoADTO", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static sop_corba.clsFormatoADTO read (org.omg.CORBA.portable.InputStream istream)
  {
    sop_corba.clsFormatoADTO value = new sop_corba.clsFormatoADTO ();
    value.codAnteproyecto = istream.read_long ();
    value.nomPrograma = istream.read_string ();
    value.tituloAnteproyecto = istream.read_string ();
    value.nomEstudiante1 = istream.read_string ();
    value.codEstudiante1 = istream.read_long ();
    value.nomEstudiante2 = istream.read_string ();
    value.codEstudiante2 = istream.read_long ();
    value.nomDirector = istream.read_string ();
    value.nomCoDirector = istream.read_string ();
    value.objetivosAnteproyecto = istream.read_string ();
    value.codDirector = istream.read_long ();
    value.flujo = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, sop_corba.clsFormatoADTO value)
  {
    ostream.write_long (value.codAnteproyecto);
    ostream.write_string (value.nomPrograma);
    ostream.write_string (value.tituloAnteproyecto);
    ostream.write_string (value.nomEstudiante1);
    ostream.write_long (value.codEstudiante1);
    ostream.write_string (value.nomEstudiante2);
    ostream.write_long (value.codEstudiante2);
    ostream.write_string (value.nomDirector);
    ostream.write_string (value.nomCoDirector);
    ostream.write_string (value.objetivosAnteproyecto);
    ostream.write_long (value.codDirector);
    ostream.write_long (value.flujo);
  }

}
