package sop_corba;


/**
* sop_corba/clsFormatoDDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* domingo 3 de octubre de 2021 07:51:32 PM COT
*/

public final class clsFormatoDDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int codAnteproyecto = (int)0;
  public String estructura = null;
  public String conceptoCoodinador = null;
  public String observaciones = null;

  public clsFormatoDDTO ()
  {
  } // ctor

  public clsFormatoDDTO (int _codAnteproyecto, String _estructura, String _conceptoCoodinador, String _observaciones)
  {
    codAnteproyecto = _codAnteproyecto;
    estructura = _estructura;
    conceptoCoodinador = _conceptoCoodinador;
    observaciones = _observaciones;
  } // ctor

} // class clsFormatoDDTO
