package sop_corba;


/**
* sop_corba/clsFormatoBDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* domingo 3 de octubre de 2021 05:25:26 PM COT
*/

public final class clsFormatoBDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int codAnteproyecto = (int)0;
  public String concepto = null;
  public String observaciones = null;
  public String fechaEvaluacion = null;
  public int idEvaluador = (int)0;

  public clsFormatoBDTO ()
  {
  } // ctor

  public clsFormatoBDTO (int _codAnteproyecto, String _concepto, String _observaciones, String _fechaEvaluacion, int _idEvaluador)
  {
    codAnteproyecto = _codAnteproyecto;
    concepto = _concepto;
    observaciones = _observaciones;
    fechaEvaluacion = _fechaEvaluacion;
    idEvaluador = _idEvaluador;
  } // ctor

} // class clsFormatoBDTO
