package sop_corba;


/**
* sop_corba/clsFormatoCDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* domingo 3 de octubre de 2021 08:29:51 PM COT
*/

public final class clsFormatoCDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int codAnteproyecto = (int)0;
  public String estructura = null;
  public String conceptoDepto = null;
  public String observaciones = null;

  public clsFormatoCDTO ()
  {
  } // ctor

  public clsFormatoCDTO (int _codAnteproyecto, String _estructura, String _conceptoDepto, String _observaciones)
  {
    codAnteproyecto = _codAnteproyecto;
    estructura = _estructura;
    conceptoDepto = _conceptoDepto;
    observaciones = _observaciones;
  } // ctor

} // class clsFormatoCDTO
