package sop_corba;

/**
* sop_corba/clsResolucionDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* domingo 3 de octubre de 2021 07:51:32 PM COT
*/

public final class clsResolucionDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.clsResolucionDTO value = null;

  public clsResolucionDTOHolder ()
  {
  }

  public clsResolucionDTOHolder (sop_corba.clsResolucionDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.clsResolucionDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.clsResolucionDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.clsResolucionDTOHelper.type ();
  }

}
