package sop_corba;

/**
* sop_corba/clsUsuariosDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* domingo 3 de octubre de 2021 08:29:51 PM COT
*/

public final class clsUsuariosDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.clsUsuariosDTO value = null;

  public clsUsuariosDTOHolder ()
  {
  }

  public clsUsuariosDTOHolder (sop_corba.clsUsuariosDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.clsUsuariosDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.clsUsuariosDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.clsUsuariosDTOHelper.type ();
  }

}
