package sop_corba;


/**
* sop_corba/GestionAnteproyectosIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* domingo 3 de octubre de 2021 07:51:32 PM COT
*/

public interface GestionAnteproyectosIntOperations 
{
  boolean registrarFormatoA (sop_corba.clsFormatoADTO objFormatoA);
  boolean AsignarFormatoB (sop_corba.clsFormatoBDTO objFormatoB);
  boolean RegistrarFormatoC (sop_corba.clsFormatoCDTO objFormatoC);
  boolean RegistrarFormatoD (sop_corba.clsFormatoDDTO objFormatoD);
  int ModificarFormatoB (sop_corba.clsFormatoBDTO objFormatoB);
  int ConsultarConceptoC (int prmCodigo);
  int ConsultarConceptoD (int prmCodigo);
  sop_corba.clsConceptosDTO consultarConceptos (int prmCodigo);
  int VerificarAnteproyecto (int prmCodigo);
  int SolicitarCodigo ();
  int ConsultarAnteproyectoB (int codigo);
  boolean verificarAsignacion (int CodAnteproyecto, int idEvaluador);
  sop_corba.clsFormatoBDTO[] listaAteproyectosAsignados (int idEvaluador);
  sop_corba.clsFormatoBDTO[] listaAteproyectosB ();
  sop_corba.clsFormatoCDTO[] listaAteproyectosC ();
  sop_corba.clsFormatoDDTO[] listaAteproyectosD ();
  sop_corba.clsFormatoADTO[] listaSinAsignar ();
  int[] listaAntNoRemitidos (int idDirector);
  boolean remitirAnteproyecto (int codAnteproyecto);
  int[] listaAntRemitidos ();
} // interface GestionAnteproyectosIntOperations
