package sop_corba;


/**
* sop_corba/GestionAnteproyectosInt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* domingo 3 de octubre de 2021 08:29:51 PM COT
*/

public interface GestionAnteproyectosInt extends GestionAnteproyectosIntOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionAnteproyectosInt
