package sop_corba;


/**
* sop_corba/GestionUsuariosIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* domingo 3 de octubre de 2021 05:25:26 PM COT
*/

public interface GestionUsuariosIntOperations 
{
  boolean RegistrarUsuario (sop_corba.clsUsuariosDTO objUsuario);
  sop_corba.clsUsuariosDTO IniciarSesion (String prmUsuario, String prmClave);
  sop_corba.clsUsuariosDTO ConsultarUsuario (int prmIdentificacion);
  boolean ModificarUsuario (sop_corba.clsUsuariosDTO objUsuario);
  int consultarEvaluador (int ID);
  sop_corba.clsUsuariosDTO[] listarEvaluadores ();
  int ValidarRegistro (int idUsuario, String usuario);
  void IniSesion (int idUsuario);
  void CerrarSesion (int idUsuario);
  int validarDecano ();
} // interface GestionUsuariosIntOperations
