package sop_corba;

/**
* sop_corba/GestionUsuariosIntHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* domingo 3 de octubre de 2021 07:51:32 PM COT
*/

public final class GestionUsuariosIntHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.GestionUsuariosInt value = null;

  public GestionUsuariosIntHolder ()
  {
  }

  public GestionUsuariosIntHolder (sop_corba.GestionUsuariosInt initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.GestionUsuariosIntHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.GestionUsuariosIntHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.GestionUsuariosIntHelper.type ();
  }

}
