package sop_corba;


/**
* sop_corba/GestionSeguimientoIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* domingo 3 de octubre de 2021 05:25:26 PM COT
*/

public interface GestionSeguimientoIntOperations 
{
  boolean RegistrarHistorial (sop_corba.clsFormatosDTO objFormatos);
  boolean RegistrarResolucion (int Codigo);
  sop_corba.clsFormatosDTO[] consultarResoluciones ();
  sop_corba.clsResolucionDTO[] consultarHistorial ();
} // interface GestionSeguimientoIntOperations
