package sop_corba;


/**
* sop_corba/GestionUsuariosIntPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* domingo 3 de octubre de 2021 08:29:51 PM COT
*/

public abstract class GestionUsuariosIntPOA extends org.omg.PortableServer.Servant
 implements sop_corba.GestionUsuariosIntOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("RegistrarUsuario", new java.lang.Integer (0));
    _methods.put ("IniciarSesion", new java.lang.Integer (1));
    _methods.put ("ConsultarUsuario", new java.lang.Integer (2));
    _methods.put ("ModificarUsuario", new java.lang.Integer (3));
    _methods.put ("consultarEvaluador", new java.lang.Integer (4));
    _methods.put ("listarEvaluadores", new java.lang.Integer (5));
    _methods.put ("ValidarRegistro", new java.lang.Integer (6));
    _methods.put ("IniSesion", new java.lang.Integer (7));
    _methods.put ("CerrarSesion", new java.lang.Integer (8));
    _methods.put ("validarDecano", new java.lang.Integer (9));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sop_corba/GestionUsuariosInt/RegistrarUsuario
       {
         sop_corba.clsUsuariosDTO objUsuario = sop_corba.clsUsuariosDTOHelper.read (in);
         boolean $result = false;
         $result = this.RegistrarUsuario (objUsuario);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // sop_corba/GestionUsuariosInt/IniciarSesion
       {
         String prmUsuario = in.read_string ();
         String prmClave = in.read_string ();
         sop_corba.clsUsuariosDTO $result = null;
         $result = this.IniciarSesion (prmUsuario, prmClave);
         out = $rh.createReply();
         sop_corba.clsUsuariosDTOHelper.write (out, $result);
         break;
       }

       case 2:  // sop_corba/GestionUsuariosInt/ConsultarUsuario
       {
         int prmIdentificacion = in.read_long ();
         sop_corba.clsUsuariosDTO $result = null;
         $result = this.ConsultarUsuario (prmIdentificacion);
         out = $rh.createReply();
         sop_corba.clsUsuariosDTOHelper.write (out, $result);
         break;
       }

       case 3:  // sop_corba/GestionUsuariosInt/ModificarUsuario
       {
         sop_corba.clsUsuariosDTO objUsuario = sop_corba.clsUsuariosDTOHelper.read (in);
         boolean $result = false;
         $result = this.ModificarUsuario (objUsuario);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // sop_corba/GestionUsuariosInt/consultarEvaluador
       {
         int ID = in.read_long ();
         int $result = (int)0;
         $result = this.consultarEvaluador (ID);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 5:  // sop_corba/GestionUsuariosInt/listarEvaluadores
       {
         sop_corba.clsUsuariosDTO $result[] = null;
         $result = this.listarEvaluadores ();
         out = $rh.createReply();
         sop_corba.GestionUsuariosIntPackage.ListaUsuariosHelper.write (out, $result);
         break;
       }

       case 6:  // sop_corba/GestionUsuariosInt/ValidarRegistro
       {
         int idUsuario = in.read_long ();
         String usuario = in.read_string ();
         int $result = (int)0;
         $result = this.ValidarRegistro (idUsuario, usuario);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 7:  // sop_corba/GestionUsuariosInt/IniSesion
       {
         int idUsuario = in.read_long ();
         this.IniSesion (idUsuario);
         out = $rh.createReply();
         break;
       }

       case 8:  // sop_corba/GestionUsuariosInt/CerrarSesion
       {
         int idUsuario = in.read_long ();
         this.CerrarSesion (idUsuario);
         out = $rh.createReply();
         break;
       }

       case 9:  // sop_corba/GestionUsuariosInt/validarDecano
       {
         int $result = (int)0;
         $result = this.validarDecano ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/GestionUsuariosInt:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GestionUsuariosInt _this() 
  {
    return GestionUsuariosIntHelper.narrow(
    super._this_object());
  }

  public GestionUsuariosInt _this(org.omg.CORBA.ORB orb) 
  {
    return GestionUsuariosIntHelper.narrow(
    super._this_object(orb));
  }


} // class GestionUsuariosIntPOA
