package sop_corba;


/**
* sop_corba/GestionAnteproyectosIntHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* domingo 3 de octubre de 2021 05:25:26 PM COT
*/

abstract public class GestionAnteproyectosIntHelper
{
  private static String  _id = "IDL:sop_corba/GestionAnteproyectosInt:1.0";

  public static void insert (org.omg.CORBA.Any a, sop_corba.GestionAnteproyectosInt that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static sop_corba.GestionAnteproyectosInt extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (sop_corba.GestionAnteproyectosIntHelper.id (), "GestionAnteproyectosInt");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static sop_corba.GestionAnteproyectosInt read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_GestionAnteproyectosIntStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, sop_corba.GestionAnteproyectosInt value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static sop_corba.GestionAnteproyectosInt narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof sop_corba.GestionAnteproyectosInt)
      return (sop_corba.GestionAnteproyectosInt)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      sop_corba._GestionAnteproyectosIntStub stub = new sop_corba._GestionAnteproyectosIntStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static sop_corba.GestionAnteproyectosInt unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof sop_corba.GestionAnteproyectosInt)
      return (sop_corba.GestionAnteproyectosInt)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      sop_corba._GestionAnteproyectosIntStub stub = new sop_corba._GestionAnteproyectosIntStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
