package sop_corba;


/**
* sop_corba/GestionUsuariosInt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* domingo 3 de octubre de 2021 05:25:26 PM COT
*/

public interface GestionUsuariosInt extends GestionUsuariosIntOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionUsuariosInt
