package cliente.vistas;

import java.rmi.RemoteException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import sop_corba.GestionAnteproyectosIntOperations;
import sop_corba.GestionSeguimientoIntOperations;
import sop_corba.GestionUsuariosIntOperations;
import sop_corba.clsUsuariosDTO;

/**
 *
 * @author Danny Alberto Diaz Mage y Jefferson Eduardo Campo Yule
 */
public class GUIInicioSesion extends javax.swing.JFrame {

    /*
    Atributos
     */
    private static GestionAnteproyectosIntOperations refGestion;
    private static GestionSeguimientoIntOperations refSeguimiento;
    private static GestionUsuariosIntOperations refUsuarios;

    /**
     * Constructor parametrizado
     *
     * @param refGestion
     * @param refSeguimiento
     * @param refUsuarios
     */
    public GUIInicioSesion(GestionAnteproyectosIntOperations refGestion, GestionSeguimientoIntOperations refSeguimiento, GestionUsuariosIntOperations refUsuarios) {
        initComponents();
        GUIInicioSesion.refGestion = refGestion;
        GUIInicioSesion.refSeguimiento = refSeguimiento;
        GUIInicioSesion.refUsuarios = refUsuarios;
    }

    /**
     * Constructor sin parametros
     */
    public GUIInicioSesion() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlbUsuario = new javax.swing.JLabel();
        jlbClave = new javax.swing.JLabel();
        jtxtFUsuario = new javax.swing.JTextField();
        btnIniciar = new javax.swing.JButton();
        jpassClave = new javax.swing.JPasswordField();
        jlbImgInicioSesion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio Sesion");
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(321, 268));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inicio de Sesion");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 28, -1, -1));

        jlbUsuario.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jlbUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jlbUsuario.setText("Usuario");
        jPanel1.add(jlbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jlbClave.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jlbClave.setForeground(new java.awt.Color(255, 255, 255));
        jlbClave.setText("Contrasenia");
        jPanel1.add(jlbClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jtxtFUsuario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(jtxtFUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 150, -1));

        btnIniciar.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        jpassClave.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(jpassClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 150, -1));

        jlbImgInicioSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iniciar sesion.png"))); // NOI18N
        jPanel1.add(jlbImgInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que obtiene la acción del botón iniciar la cual accede a las
     * funciones de acuerdo con el rol
     *
     * @param evt
     */
    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        String usuario = "admin";
        String clave = "admin123";

        if (jtxtFUsuario.getText().equals("") || jpassClave.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }else if (jtxtFUsuario.getText().equals(usuario) && jpassClave.getText().equals(clave)) {
            GUIMenuAdministrador pru = new GUIMenuAdministrador(refGestion, refSeguimiento, refUsuarios);
            pru.setVisible(true);
            pru.setLocationRelativeTo(null);
            this.dispose();
        } else {
            try {
                String user = jtxtFUsuario.getText();
                String pass = new String(jpassClave.getPassword());
                clsUsuariosDTO objUsuario = refUsuarios.IniciarSesion(user, pass);
                //retornar un valor en -1 para reconocer el objeto
                if (objUsuario.identificacion == -1) {

                    JOptionPane.showMessageDialog(null, "Credenciales Incorrectas.", "Error al validar credenciales", JOptionPane.ERROR_MESSAGE);

                } else if (objUsuario.sesion) {
                    JOptionPane.showMessageDialog(null, "Ya existe una sesion abierta para este usuario", "Error al iniciar sesion", JOptionPane.ERROR_MESSAGE);
                } else {
                    String rolUsuario = objUsuario.role;
                    String nomUsuario = objUsuario.nomCompleto;

                    switch (rolUsuario) {

                        case "Director":
                            int idDirector = objUsuario.identificacion;
                            refUsuarios.IniSesion(idDirector);
                            GUIMenuDirector menuDirector = new GUIMenuDirector(refGestion, refSeguimiento, refUsuarios, idDirector, nomUsuario);
                            menuDirector.setVisible(true);
                            menuDirector.setLocationRelativeTo(null);
                            this.dispose();
                            break;

                        case "Evaluador":
                            int idEvaluador = objUsuario.identificacion;
                            GUIMenuEvaluador menuEvaluador = new GUIMenuEvaluador(refGestion, refSeguimiento, refUsuarios, idEvaluador);
                            menuEvaluador.setVisible(true);
                            menuEvaluador.setLocationRelativeTo(null);
                            this.dispose();
                            break;

                        case "Jefe Departamento":
                            GUIMenuJefeDepartamento menuJDepartamento = new GUIMenuJefeDepartamento(refGestion, refSeguimiento, refUsuarios);
                            menuJDepartamento.setVisible(true);
                            menuJDepartamento.setLocationRelativeTo(null);
                            this.dispose();
                            break;

                        case "Coordinador":
                            GUIMenuCoordinador menuCoordinador = new GUIMenuCoordinador(refGestion, refSeguimiento, refUsuarios);
                            menuCoordinador.setVisible(true);
                            menuCoordinador.setLocationRelativeTo(null);
                            this.dispose();
                            break;

                        case "Decano":
                            GUIMenuDecano menuDecano = new GUIMenuDecano(refGestion, refSeguimiento, refUsuarios);
                            menuDecano.setVisible(true);
                            menuDecano.setLocationRelativeTo(null);
                            this.dispose();
                            break;
                        default:
                            JOptionPane.showMessageDialog(null, "Rol No existente");
                            break;
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "La operacion no se pudo completar, intente nuevamente..." + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIInicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlbClave;
    private javax.swing.JLabel jlbImgInicioSesion;
    private javax.swing.JLabel jlbUsuario;
    private javax.swing.JPasswordField jpassClave;
    private javax.swing.JTextField jtxtFUsuario;
    // End of variables declaration//GEN-END:variables
}
