/**
 * Presentado por: Jefferson Eduardo Campo Y Danny Alberto Diaz Mage
 */
package cliente.vistas;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sop_corba.GestionAnteproyectosIntOperations;
import sop_corba.GestionSeguimientoIntOperations;
import sop_corba.GestionUsuariosIntOperations;
import sop_corba.clsFormatosDTO;
import sop_corba.clsResolucionDTO;

public class GUIMenuDecano extends javax.swing.JFrame {
    //Atributos
    private static GestionAnteproyectosIntOperations refGestion;
    private static GestionSeguimientoIntOperations refSeguimiento;
    private static GestionUsuariosIntOperations refUsuarios;

    /**
     * Constructor vacio.
     */
    public GUIMenuDecano() {}

    /**
     * Constructor parametrizado
     * @param refGestion
     * @param refSeguimiento
     * @param refUsuarios
     */
    public GUIMenuDecano(GestionAnteproyectosIntOperations refGestion, GestionSeguimientoIntOperations refSeguimiento, GestionUsuariosIntOperations refUsuarios) {
        initComponents();
        GUIMenuDecano.refGestion = refGestion;
        GUIMenuDecano.refSeguimiento = refSeguimiento;
        GUIMenuDecano.refUsuarios = refUsuarios;
        listarAntSinResolucion();
        llenaCmbAnteproyectos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlbBSalirReg = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pnlHistorial = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jcmbAnteproyectos = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        jlbImgRegResolucion = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        pnlHistorialRes = new javax.swing.JTable();
        btnConsultar = new javax.swing.JButton();
        jlbBSalirConRes = new javax.swing.JLabel();
        jlbImgConResolucion = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlFormatoA = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jlbTituloA = new javax.swing.JLabel();
        jlbTituloB = new javax.swing.JLabel();
        jlbTituloC = new javax.swing.JLabel();
        jlbTituloD = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        pnlFormatoB = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        pnlFormatoC = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        pnlFormatoD = new javax.swing.JTable();
        btnConHistorial = new javax.swing.JButton();
        jlbImgConHistorialGen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu del Decano");
        setResizable(false);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Registrar resolucion");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Listar anteproyectos");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Registrar");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, -1));

        jlbBSalirReg.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlbBSalirReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/CerrarSesion.png"))); // NOI18N
        jlbBSalirReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbBSalirRegMouseClicked(evt);
            }
        });
        jPanel4.add(jlbBSalirReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 770, 50, 70));

        pnlHistorial.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        pnlHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Titulo", "Programa"
            }
        ));
        jScrollPane2.setViewportView(pnlHistorial);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 922, 168));

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Codigo del anteproyecto");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, -1, 30));

        jcmbAnteproyectos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel4.add(jcmbAnteproyectos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, 400, 30));

        btnRegistrar.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 15)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel4.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 540, -1, 30));

        jlbImgRegResolucion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/registrarResolucion.png"))); // NOI18N
        jPanel4.add(jlbImgRegResolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 850));

        jTabbedPane1.addTab("Registrar resolucion", jPanel4);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 26)); // NOI18N
        jLabel1.setText("Consultar Historial Resoluciones");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        jScrollPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnlHistorialRes.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        pnlHistorialRes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Numero de Resolucion", "Fecha", "Codigo"
            }
        ));
        pnlHistorialRes.setRequestFocusEnabled(false);
        jScrollPane3.setViewportView(pnlHistorialRes);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 660, 310));

        btnConsultar.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 15)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 690, -1, -1));

        jlbBSalirConRes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlbBSalirConRes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/CerrarSesion.png"))); // NOI18N
        jlbBSalirConRes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbBSalirConResMouseClicked(evt);
            }
        });
        jPanel1.add(jlbBSalirConRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 790, -1, -1));

        jlbImgConResolucion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/consultar resolucion.png"))); // NOI18N
        jPanel1.add(jlbImgConResolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 860));

        jTabbedPane1.addTab("Consultar Resolucion", jPanel1);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pnlFormatoA.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        pnlFormatoA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Programa", "Titulo", "Cod. Estudiante 1", "Estudiante 1", "Cod. Estudiante 2", "Estudiante 2", "Director", "Codirector", "Observaciones"
            }
        ));
        jScrollPane1.setViewportView(pnlFormatoA);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 986, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 990, 170));

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 26)); // NOI18N
        jLabel6.setText("Consultar Historial");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jlbTituloA.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        jlbTituloA.setText("FormatoTI-A");
        jPanel5.add(jlbTituloA, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, -1));

        jlbTituloB.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        jlbTituloB.setText("FormatoTI-B");
        jPanel5.add(jlbTituloB, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, -1, -1));

        jlbTituloC.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        jlbTituloC.setForeground(new java.awt.Color(255, 255, 255));
        jlbTituloC.setText("FormatoTI-C");
        jPanel5.add(jlbTituloC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, -1, -1));

        jlbTituloD.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        jlbTituloD.setForeground(new java.awt.Color(255, 255, 255));
        jlbTituloD.setText("FormatoTI-D");
        jPanel5.add(jlbTituloD, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 510, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/CerrarSesion.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 800, -1, -1));

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pnlFormatoB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo Ant", "ID evaluador 1", "Concepto", "Fecha de Evaluacion", "Observaciones", "ID Evaluador 2", "Concepto", "Fecha de Evaluacion", "Observaciones"
            }
        ));
        jScrollPane4.setViewportView(pnlFormatoB);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 986, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 990, 190));

        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pnlFormatoC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Concepto Jefe Depto", "Estructura", "Observaciones"
            }
        ));
        jScrollPane6.setViewportView(pnlFormatoC);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 510, 190));

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pnlFormatoD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Concepto Coordinador", "Estructura", "Observaciones"
            }
        ));
        jScrollPane5.setViewportView(pnlFormatoD);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 540, 460, 190));

        btnConHistorial.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 15)); // NOI18N
        btnConHistorial.setText("Consultar Historial");
        btnConHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConHistorialActionPerformed(evt);
            }
        });
        jPanel5.add(btnConHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 750, -1, -1));

        jlbImgConHistorialGen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/consultar resolucion.png"))); // NOI18N
        jPanel5.add(jlbImgConHistorialGen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 860));

        jTabbedPane1.addTab("Consultar Historial", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 877, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que captura el evento del botón registrar al efectuar un click, y posteriormente
     * registra en el historial el anteproyecto.
     * @param evt evento.
     */
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        boolean bandera = false;
        try {
            if (jcmbAnteproyectos.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(null, "Campos vacios, debe completar el codigo del anteproyecto","Advertencia",JOptionPane.WARNING_MESSAGE);
            } else {
                int idCodigo = Integer.parseInt(jcmbAnteproyectos.getSelectedItem().toString());
                ArrayList<clsFormatosDTO> listaFormatos = obtenerLista();
                for (int i = 0; i < listaFormatos.size(); i++) {
                    if (listaFormatos.get(i).codAnteproyecto == idCodigo) {
                        bandera = true;
                    }
                }
                if (bandera) {
                    boolean registro = refSeguimiento.RegistrarResolucion(idCodigo);
                    if (registro == true) {
                        JOptionPane.showMessageDialog(null, "registrado exitosamente");
                        listarAntSinResolucion();
                        jcmbAnteproyectos.removeAllItems();
                        llenaCmbAnteproyectos();
                    } else {
                        JOptionPane.showMessageDialog(null, "No se pudo registar", "Error al registrar", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    boolean band = false;
                    clsFormatosDTO[] listaFormatos2 = refSeguimiento.consultarHistorial();
                    for (int i = 0; i < listaFormatos2.length; i++) {
                        if (listaFormatos2[i].codAnteproyecto == idCodigo) {
                            JOptionPane.showMessageDialog(null, "Este anteproyecto ya fue registrado", "Error en la busqueda", JOptionPane.ERROR_MESSAGE);
                            band = true;
                            break;
                        }
                    }
                    if (!band) {
                        JOptionPane.showMessageDialog(null, "No hay anteproyectos para generar resolución", "Error en la busqueda", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "La operacion no se pudo completar, intente nuevamente..." + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * Método que captura el evento del botón consultar al efectuar un click, y posteriormente
     * obtiene el historial de las resoluciones.
     * @param evt evento.
     */
    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        try {
            clsResolucionDTO[] arrayResol = refSeguimiento.consultarResoluciones();
            ArrayList<clsResolucionDTO> listaResolucion = new ArrayList(Arrays.asList(arrayResol));
            DefaultTableModel modelo = new DefaultTableModel();
            if (listaResolucion.isEmpty()) {
                JOptionPane.showMessageDialog(null, "No hay anteproyectos aprobados", "Advertencia", JOptionPane.WARNING_MESSAGE);
                modelo.addColumn("Numero de resolucion");
                modelo.addColumn("Fecha");
                modelo.addColumn("Codigo");
                Object[] obj = new Object[]{"", "", ""};
                modelo.addRow(obj);
                pnlHistorialRes.setModel(modelo);
            } else {
                modelo.addColumn("Numero de resolucion");
                modelo.addColumn("Fecha");
                modelo.addColumn("Codigo");
                for (int i = 0; i < listaResolucion.size(); i++) {
                    clsResolucionDTO resolucion = listaResolucion.get(i);
                    Object[] obj = new Object[]{resolucion.numResolucion, resolucion.fecha, resolucion.codAnteproyecto};
                    modelo.addRow(obj);
                }
                pnlHistorialRes.setModel(modelo);
            }
        }catch (Exception ex) {
            Logger.getLogger(GUIMenuDecano.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    /**
     * Método que captura el evento del mouse o ratón al efectuar un click en el botón salir del formulario
     * registrar.
     * @param evt evento.
     */
    private void jlbBSalirRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbBSalirRegMouseClicked
        GUIInicioSesion ini = new GUIInicioSesion(refGestion,refSeguimiento,refUsuarios);
        ini.setVisible(true);
        ini.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jlbBSalirRegMouseClicked
    
    /**
     * Método que captura el evento del mouse o ratón al efectuar un click en el botón salir del formulario
     * consultar resolución.
     * @param evt evento.
     */
    private void jlbBSalirConResMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbBSalirConResMouseClicked
        GUIInicioSesion ini = new GUIInicioSesion(refGestion,refSeguimiento,refUsuarios);
        ini.setVisible(true);
        ini.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jlbBSalirConResMouseClicked

    /**
     * Método que captura el evento del mouse o ratón al efectuar un click en el botón salir del formulario
     * consultar historial.
     * @param evt 
     */
    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        GUIInicioSesion ini = new GUIInicioSesion(refGestion,refSeguimiento,refUsuarios);
        ini.setVisible(true);
        ini.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * Método que captura el evento del botón consultar al efectuar un click, y posteriormente
     * obtiene el historial de todos los anteproyectos.
     * @param evt evento.
     */
    private void btnConHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConHistorialActionPerformed
        try {
            listarAnteproyectos();
        } catch (IOException ex) {
            Logger.getLogger(GUIMenuDecano.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConHistorialActionPerformed

    /**
     * Este método obtiene el historial de resoluciones y los lista en la GUI del decano
     * @throws FileNotFoundException en caso de que no se encuentre el archivo txt.
     * @throws IOException en caso de que no pueda leer el txt.
     */
    private void listarAnteproyectos() throws FileNotFoundException, IOException {
        clsFormatosDTO[] arrayForms = refSeguimiento.consultarHistorial();
        ArrayList<clsFormatosDTO> listaFormatos = new ArrayList<>(Arrays.asList(arrayForms));
        DefaultTableModel modelo = new DefaultTableModel();
        DefaultTableModel modelo1 = new DefaultTableModel();
        DefaultTableModel modelo2 = new DefaultTableModel();
        DefaultTableModel modelo3 = new DefaultTableModel();
        if (listaFormatos.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No hay anteproyectos registrados en el historial", "Advertencia", JOptionPane.WARNING_MESSAGE);
            modelo.addColumn("Código");
            modelo.addColumn("Programa");
            modelo.addColumn("Titulo");
            modelo.addColumn("Cod estudiante 1");
            modelo.addColumn("Estudiante 1");
            modelo.addColumn("Cod estudiante 2");
            modelo.addColumn("Estudiante 2");
            modelo.addColumn("Director");
            modelo.addColumn("Codirector");
            modelo.addColumn("Observaciones");
            modelo1.addColumn("Codigo Ant");
            modelo1.addColumn("Id evaluador 1");
            modelo1.addColumn("concepto ");
            modelo1.addColumn("Fecha evaluación");
            modelo1.addColumn("Observaciones");
            modelo1.addColumn("Id evaluador 2");
            modelo1.addColumn("concepto ");
            modelo1.addColumn("Fecha evaluación");
            modelo1.addColumn("Observaciones");
            modelo2.addColumn("Codigo");
            modelo2.addColumn("Concepto Jefe Depto");
            modelo2.addColumn("Estructura");
            modelo2.addColumn("Observaciones");
            modelo3.addColumn("Codigo");
            modelo3.addColumn("Concepto Coordinador");
            modelo3.addColumn("Estructura");
            modelo3.addColumn("Observaciones");
            pnlFormatoA.setModel(modelo);
            pnlFormatoB.setModel(modelo1);
            pnlFormatoC.setModel(modelo2);
            pnlFormatoD.setModel(modelo3);
        } else {
            modelo.addColumn("Código");
            modelo.addColumn("Programa");
            modelo.addColumn("Titulo");
            modelo.addColumn("Cod estudiante 1");
            modelo.addColumn("Estudiante 1");
            modelo.addColumn("Cod estudiante 2");
            modelo.addColumn("Estudiante 2");
            modelo.addColumn("Director");
            modelo.addColumn("Codirector");
            modelo.addColumn("Observaciones");
            modelo1.addColumn("Codigo Ant");
            modelo1.addColumn("Id evaluador 1");
            modelo1.addColumn("concepto ");
            modelo1.addColumn("Fecha evaluación");
            modelo1.addColumn("Observaciones");
            modelo1.addColumn("Id evaluador 2");
            modelo1.addColumn("concepto ");
            modelo1.addColumn("Fecha evaluación");
            modelo1.addColumn("Observaciones");
            modelo2.addColumn("Codigo");
            modelo2.addColumn("Concepto Jefe Depto");
            modelo2.addColumn("Estructura");
            modelo2.addColumn("Observaciones");
            modelo3.addColumn("Codigo");
            modelo3.addColumn("Concepto Coordinador");
            modelo3.addColumn("Estructura");
            modelo3.addColumn("Observaciones");
            for (int i = 0; i < listaFormatos.size(); i++) {
                clsFormatosDTO formatos = listaFormatos.get(i);
                Object[] obj = new Object[]{formatos.codAnteproyecto, formatos.formatoA.nomPrograma,
                    formatos.formatoA.tituloAnteproyecto, formatos.formatoA.codEstudiante1,
                    formatos.formatoA.nomEstudiante1, formatos.formatoA.codEstudiante2, formatos.formatoA.nomEstudiante2,
                    formatos.formatoA.nomDirector, formatos.formatoA.nomCoDirector, formatos.formatoA.objetivosAnteproyecto};
                modelo.addRow(obj);
                Object[] obj2 = new Object[]{formatos.formatoB1.codAnteproyecto, formatos.formatoB1.idEvaluador, formatos.formatoB1.concepto, formatos.formatoB1.fechaEvaluacion,
                    formatos.formatoB1.observaciones, formatos.formateB2.idEvaluador, formatos.formateB2.concepto, formatos.formateB2.fechaEvaluacion,
                    formatos.formateB2.observaciones};
                modelo1.addRow(obj2);
                Object[] obj3 = new Object[]{formatos.formatoC.codAnteproyecto, formatos.formatoC.conceptoDepto, formatos.formatoC.estructura, formatos.formatoC.observaciones};
                modelo2.addRow(obj3);
                Object[] obj4 = new Object[]{formatos.formatoD.codAnteproyecto, formatos.formatoD.conceptoCoodinador, formatos.formatoD.estructura, formatos.formatoD.observaciones};
                modelo3.addRow(obj4);
            }
            pnlFormatoA.setModel(modelo);
            pnlFormatoB.setModel(modelo1);
            pnlFormatoC.setModel(modelo2);
            pnlFormatoD.setModel(modelo3);
        }
    }
    
    /**
     * Método que obtiene la lista de anteproyectos los cuales ya tienen registrada una resolución. 
     * @return 
     */
    private ArrayList<clsFormatosDTO> obtenerLista() {
        
        clsFormatosDTO[] arrayFormatos = refSeguimiento.consultarHistorial();
        ArrayList<clsFormatosDTO> listaFormatos = new ArrayList(Arrays.asList(arrayFormatos));   
        try {
            clsResolucionDTO[] arrayResoluciones = refSeguimiento.consultarResoluciones();
            ArrayList<clsResolucionDTO> listaResolucion = new ArrayList(Arrays.asList(arrayResoluciones));
            for (int j = 0; j < listaResolucion.size(); j++) {
                for (int i = 0; i < listaFormatos.size(); i++) {
                    if (listaFormatos.get(i).codAnteproyecto == Integer.parseInt(listaResolucion.get(j).codAnteproyecto)) {
                        listaFormatos.remove(i);
                    }
                }
            }
        }catch (Exception ex) {
            Logger.getLogger(GUIMenuDecano.class.getName()).log(Level.SEVERE, null, ex);
        }
        return listaFormatos;
    }

    /**
     * Método que completa los campos de combo box para que puedan ser seleccionados por el usuario.
     */
    public void llenaCmbAnteproyectos() {
        ArrayList<clsFormatosDTO> listaFormatos = obtenerLista();
        for (int i = 0; i < listaFormatos.size(); i++) {
            String codAnte = String.valueOf(listaFormatos.get(i).codAnteproyecto);
            jcmbAnteproyectos.addItem(codAnte);
        }
    }

    /**
     * Método que lista los anteproyectos que no tienen resolución. 
     */
    private void listarAntSinResolucion() {
        ArrayList<clsFormatosDTO> listaFormatos = obtenerLista();
        DefaultTableModel modelo = new DefaultTableModel();
        if (listaFormatos.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No hay anteproyectos aprobados", "Advertencia", JOptionPane.WARNING_MESSAGE);
            modelo.addColumn("Codigo");
            modelo.addColumn("Titulo");
            modelo.addColumn("Programa");
            Object[] obj = new Object[]{};
            modelo.addRow(obj);
            pnlHistorial.setModel(modelo);
        } else {
            modelo.addColumn("Codigo");
            modelo.addColumn("Titulo");
            modelo.addColumn("Programa");
            for (int i = 0; i < listaFormatos.size(); i++) {
                clsFormatosDTO formatos = listaFormatos.get(i);
                Object[] obj = new Object[]{formatos.codAnteproyecto, formatos.formatoA.tituloAnteproyecto, formatos.formatoA.nomPrograma};
                modelo.addRow(obj);
            }
            pnlHistorial.setModel(modelo);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMenuDecano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMenuDecano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMenuDecano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMenuDecano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIMenuDecano().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConHistorial;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> jcmbAnteproyectos;
    private javax.swing.JLabel jlbBSalirConRes;
    private javax.swing.JLabel jlbBSalirReg;
    private javax.swing.JLabel jlbImgConHistorialGen;
    private javax.swing.JLabel jlbImgConResolucion;
    private javax.swing.JLabel jlbImgRegResolucion;
    private javax.swing.JLabel jlbTituloA;
    private javax.swing.JLabel jlbTituloB;
    private javax.swing.JLabel jlbTituloC;
    private javax.swing.JLabel jlbTituloD;
    private javax.swing.JTable pnlFormatoA;
    private javax.swing.JTable pnlFormatoB;
    private javax.swing.JTable pnlFormatoC;
    private javax.swing.JTable pnlFormatoD;
    private javax.swing.JTable pnlHistorial;
    private javax.swing.JTable pnlHistorialRes;
    // End of variables declaration//GEN-END:variables
}
