//Presentado por: Jefferson Eduardo Campo - Danny Alberto Diaz
package SGestionAnteproyectos.vistas;

import SGestionAnteproyectos.sop_rmi.GestionAnteproyectosImpl;
import SGestionAnteproyectos.sop_rmi.GestionUsuariosImpl;
import SGestionAnteproyectos.utilidades.UtilidadesRegistroS;
import javax.swing.JOptionPane;

public class GUIConectarServidorGestion extends javax.swing.JFrame {

    /**
     * Creates new form GUIConectarServidor1
     */
    public GUIConectarServidorGestion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnConectar = new javax.swing.JButton();
        jlbDireccionIp = new javax.swing.JLabel();
        jlbPuerto = new javax.swing.JLabel();
        jtxtFDirIp = new javax.swing.JTextField();
        jtxtFPuerto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conectar Servidor de Gestion");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 26)); // NOI18N
        jLabel1.setText("Conectar Servidor Gestion");

        btnConectar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnConectar.setText("Conectar");
        btnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarActionPerformed(evt);
            }
        });

        jlbDireccionIp.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jlbDireccionIp.setText("Direccion IP");

        jlbPuerto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jlbPuerto.setText("Puerto");

        jtxtFDirIp.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jtxtFPuerto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtFDirIp, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(jtxtFPuerto)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jlbDireccionIp))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jlbPuerto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnConectar)
                .addGap(117, 117, 117))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbDireccionIp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtFDirIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbPuerto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtFPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConectar)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento utilizado para conectar el servidor de gestion de anteproyectos
     * @param evt 
     */
    private void btnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarActionPerformed
        // TODO add your handling code here:
        String mensajeRegistroOR;
        String mensajeRecuperarRefUsuario;
        String mensajeRecuperarRef;
        String mensajeRegistroORUsuario;
        
        int puerto = Integer.parseInt(jtxtFPuerto.getText());

        try {
            GestionAnteproyectosImpl objRemoto = new GestionAnteproyectosImpl();
            mensajeRecuperarRef = objRemoto.consultarReferenciaRemota(jtxtFDirIp.getText() , puerto);            
            mensajeRegistroOR = UtilidadesRegistroS.RegistrarObjetoRemoto(objRemoto, jtxtFDirIp.getText() , puerto, "objetoRemotoGestion");
            
            GestionUsuariosImpl objRemotoUsuarios = new GestionUsuariosImpl();
            mensajeRecuperarRefUsuario = objRemotoUsuarios.consultarReferenciaRemota(jtxtFDirIp.getText(), puerto);
            mensajeRegistroORUsuario = UtilidadesRegistroS.RegistrarObjetoRemoto(objRemotoUsuarios, jtxtFDirIp.getText(), puerto, "objetoRemotoUsuario");
            
            GUIInfoServidor1 info1 = new GUIInfoServidor1();
            info1.setVisible(true);
            info1.setLocationRelativeTo(null);
            String mensaje = mensajeRecuperarRef + "\n" + mensajeRegistroOR + "\n" + mensajeRecuperarRefUsuario + "\n" + mensajeRegistroORUsuario;
            info1.jtxtAMensaje1.setText(mensaje);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No fue posible arrancar el NS o registrar el objeto remoto" + e.getMessage());
            System.err.println("No fue posible arrancar el NS o registrar el objeto remoto" + e.getMessage());
        }
        
    }//GEN-LAST:event_btnConectarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIConectarServidorGestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIConectarServidorGestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIConectarServidorGestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIConectarServidorGestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIConectarServidorGestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConectar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlbDireccionIp;
    private javax.swing.JLabel jlbPuerto;
    private javax.swing.JTextField jtxtFDirIp;
    private javax.swing.JTextField jtxtFPuerto;
    // End of variables declaration//GEN-END:variables
}
