//Presentado por: Jefferson Eduardo Campo - Danny Alberto Diaz
package SSeguimientoAnteproyectos.vistas;

import SSeguimientoAnteproyectos.utilidades.UtilidadesRegistroS;
import SSeguimientoAnteproyectos.sop_rmi.GestionSeguimientoImpl;
import javax.swing.JOptionPane;

public class GUIConectarServidorSeguimiento extends javax.swing.JFrame {

    /**
     * Creates new form GUIConectarServidor2
     */
    public GUIConectarServidorSeguimiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlbDireccionIPS = new javax.swing.JLabel();
        jlbPuertoS = new javax.swing.JLabel();
        btnConectarS = new javax.swing.JButton();
        jtxtFDirIpS = new javax.swing.JTextField();
        jtxtFPuertoS = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conectar Servidor Seguimiento");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Conectar Servidor Seguimiento");

        jlbDireccionIPS.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbDireccionIPS.setText("Direccion IP");

        jlbPuertoS.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlbPuertoS.setText("Puerto");

        btnConectarS.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnConectarS.setText("Conectar");
        btnConectarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarSActionPerformed(evt);
            }
        });

        jtxtFDirIpS.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jtxtFPuertoS.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jlbDireccionIPS))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jlbPuertoS))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtFPuertoS, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtFDirIpS, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btnConectarS)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jlbDireccionIPS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtFDirIpS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlbPuertoS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtFPuertoS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConectarS)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento generado para conectar el servidor 
     */
    private void btnConectarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarSActionPerformed
        // TODO add your handling code here:
        String mensajeRegistroOR;
        String mensajeArrancarNS;
        
        int puerto = Integer.parseInt(jtxtFPuertoS.getText());
        try{
            GestionSeguimientoImpl objRemoto = new GestionSeguimientoImpl();
            mensajeArrancarNS = UtilidadesRegistroS.arrancarNS(jtxtFDirIpS.getText(),puerto);
            mensajeRegistroOR = UtilidadesRegistroS.RegistrarObjetoRemoto(objRemoto, jtxtFDirIpS.getText(), puerto, "objetoRemotoSeguimiento");
            GUIInfoServidor2 info2 = new GUIInfoServidor2();
            info2.setVisible(true);
            info2.setLocationRelativeTo(null);
            String mensaje = mensajeArrancarNS+"\n" + mensajeRegistroOR+"\n";
            info2.jtxtAMensaje2.setText(mensaje);
            this.dispose();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "No fue posible arrancar el NS o registrar el objeto remoto" + e.getMessage());
            System.err.println("No fue posible arrancar el NS o registrar el objeto remoto" + e.getMessage());
            
        }
    }//GEN-LAST:event_btnConectarSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIConectarServidorSeguimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIConectarServidorSeguimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIConectarServidorSeguimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIConectarServidorSeguimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIConectarServidorSeguimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConectarS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlbDireccionIPS;
    private javax.swing.JLabel jlbPuertoS;
    private javax.swing.JTextField jtxtFDirIpS;
    private javax.swing.JTextField jtxtFPuertoS;
    // End of variables declaration//GEN-END:variables
}
