package sop_corba.GestionAnteproyectosIntPackage;


/**
* sop_corba/GestionAnteproyectosIntPackage/formatosDHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* domingo 3 de octubre de 2021 07:51:32 PM COT
*/

public final class formatosDHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.clsFormatoDDTO value[] = null;

  public formatosDHolder ()
  {
  }

  public formatosDHolder (sop_corba.clsFormatoDDTO[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.GestionAnteproyectosIntPackage.formatosDHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.GestionAnteproyectosIntPackage.formatosDHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.GestionAnteproyectosIntPackage.formatosDHelper.type ();
  }

}
