package sop_corba.GestionAnteproyectosIntPackage;


/**
* sop_corba/GestionAnteproyectosIntPackage/formatosAHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* domingo 3 de octubre de 2021 08:29:51 PM COT
*/

public final class formatosAHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.clsFormatoADTO value[] = null;

  public formatosAHolder ()
  {
  }

  public formatosAHolder (sop_corba.clsFormatoADTO[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.GestionAnteproyectosIntPackage.formatosAHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.GestionAnteproyectosIntPackage.formatosAHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.GestionAnteproyectosIntPackage.formatosAHelper.type ();
  }

}
