package sop_corba.GestionAnteproyectosIntPackage;


/**
* sop_corba/GestionAnteproyectosIntPackage/listaAnteproyectosNoRemitidosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* domingo 3 de octubre de 2021 07:51:32 PM COT
*/

public final class listaAnteproyectosNoRemitidosHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public listaAnteproyectosNoRemitidosHolder ()
  {
  }

  public listaAnteproyectosNoRemitidosHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.GestionAnteproyectosIntPackage.listaAnteproyectosNoRemitidosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.GestionAnteproyectosIntPackage.listaAnteproyectosNoRemitidosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.GestionAnteproyectosIntPackage.listaAnteproyectosNoRemitidosHelper.type ();
  }

}
